<?php
/*
 * INCIANDO SISTEMAS DE ROTAS DO FRAMEWORK, VOCÊ DEVE PASSAR AS ROTAS
 * NO SEGUINTE FORMATO ['/ROTA', 'CONTROLLER@METODO']
 * CASO QUEIRA PASSAR REQUISIÇÕES BASTAS SEUS METODOS RECEBEREM AS MESMAS,
 * NÃO É NECESSARIO DEIXAR ISSO CLARO EM SUAS ROTAS.
 */

/* NAO MECHER ROTAS DEDICADAS A API
 * DA SMARTDRAGON PARA CLIENTES QUE CONTRATAM
 * O ARQUIVO PURIFICADO PARA GERAR SUAS PROPRIAS INTEGRAÇÕES
 */
$routes[] = ['/api', 'ApiController@login'];
/* -ATENÇÃO :
 * A ROTA / NÃO PODE RECEBER PARAMETROS VIA URL POIS ELA NAO ESTA ACESSANDO
 * UM METODO ESPECIFICO, PARA RECEBER PARAMETROS VIA URL SOMENTE DEMAIS ROTAS
 */

$routes[] = ['/', 'IndexController@index'];
return $routes;
